protected/controllers/UserController.php
<?php

class UserController extends Controller
{
  public $layout='//layouts/main';

  /**
   * @return array action filters
   */
  public function filters()
  {
    return array(
		 'accessControl', // perform access control for CRUD operations
		 'postOnly + delete', // we only allow deletion via POST request
		 );
  }

  /**
   * Specifies the access control rules.
   * This method is used by the 'accessControl' filter.
   * @return array access control rules
   */
  public function accessRules()
  {
    return array(
		 /*array('allow',  // allow all users to perform 'index' and 'view' actions
		   'actions'=>array('index','view'),
		   'users'=>array('*'),
		   ),*/
		 array('allow', // allow anonymous users to perform 'create' and 'view' actions
		       'actions'=>array('create','view','viewbyname'),
		       'users'=>array('?'),
		       ),
		 array('allow', //Allow only authenticated users to update 
		       'actions'=>array('update','view','viewbyname'),
		       'users'=>array('@'),
		       ),
		 array('allow', // allow admin user do anything they feel like.
		       'users'=>array('vados'),
		       ),
		 array('deny',  // deny all users
		       'users'=>array('*'),
		       ),
		 );
  }

  /**
   * Displays a particular model.
   * @param integer $id the ID of the model to be displayed
   */
  public function actionView($id)
  {
    $this->render('view',array(
			       'model'=>$this->loadUserById($id),
			       ));
  }

  /**
   * Look up and display a user's data by username
   * @param string $username The username of the User to be retrieved
   */
  public function actionViewByName($username)
  {
      $this->render('view',array(
				 'model'=>$this->loadUserByName($username),
				 ));
  }

  /**
   * Creates a new model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   */
  public function actionCreate()
  {

    //Disable user creation -- redirect to beta signup
    $this->redirect(array('site/betasignup'));

    $model=new User;
    $userinfo=new UserInfo;

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if(isset($_POST['User']) && isset($_POST['UserInfo']))
      {
	$model->attributes=$_POST['User'];
	$userinfo->attributes=$_POST['UserInfo'];

	$newrecord = $model->isNewRecord;
	
	//Hash the password using phpass before storing it
	$hasher = new PasswordHash(8,FALSE);	
	$model->password = $hasher->HashPassword($model->password);

	if($model->save()){
	  //Save the userinfo with the model id
	  $userinfo->user_id = $model->user_id;
	  $userinfo->save();

	  $this->redirect(array('site/login','new'=>true)); //Redirect to login so they can log in
	} else {
	  $model->password = '';
	}
      }

    $this->render('create',array(
				 'model'=>$model,
				 'userinfo'=>$userinfo,
				 ));
  }

  /**
   * Updates a particular model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id the ID of the model to be updated
   */
  public function actionUpdate($id)
  {

    //Error if non-admin user tries to update someone else's info
    if (Yii::app()->user->name !== 'vados' && Yii::app()->user->id !== $id){
      throw new CHttpException('401', 'Access Denied');
    }

    //Load the user & userinfo models
    $model=$this->loadUserById($id);
    $userinfo = UserInfo::model()->findByPk($id);

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if(isset($_POST['User']) && isset($_POST['UserInfo']))
      {
	//Update the user model
	$model->attributes=$_POST['User'];

	//Update the user info model
	$userinfo->attributes=$_POST['UserInfo'];

	if($model->save() && $userinfo->save())
	  $this->redirect(array('viewbyname','username'=>$model->username));
      }

    $this->render('update',array(
				 'model'=>$model,
				 'userinfo'=>$userinfo,
				 ));
  }

  /**
   * Deletes a particular model.
   * If deletion is successful, the browser will be redirected to the 'admin' page.
   * @param integer $id the ID of the model to be deleted
   */
  public function actionDelete($id)
  {
    $this->loadUserById($id)->delete();

    // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
    if(!isset($_GET['ajax']))
      $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('vados'));
  }

  /**
   * Lists all models.
   */
  public function actionIndex()
  {
    $dataProvider=new CActiveDataProvider('User');
    $this->render('index',array(
				'dataProvider'=>$dataProvider,
				));
  }

  /**
   * Manages all models.
   */
  public function actionAdmin()
  {
    $model=new User('search');
    $model->unsetAttributes();  // clear any default values
    if(isset($_GET['User']))
      $model->attributes=$_GET['User'];

    $this->render('admin',array(
				'model'=>$model,
				));
  }

  /**
   * Returns the User based on the primary key given in the GET variable.
   * If the data model is not found, an HTTP exception will be raised.
   * @param integer id The ID of the model to be loaded
   */
  public function loadUserById($id)
  {
    $model=User::model()->findByPk($id);
    if($model===null)
      throw new CHttpException('404','The requested page does not exist.');
    return $model;
  }

  /**
   * Returns the User based on the primary key given in the GET variable.
   * If the data model is not found, an HTTP exception will be raised.
   * @param integer username The username of the model to be loaded
   */
  public function loadUserByName($username)
  {
    $model=User::model()->findByAttributes(array('username'=>$username));
    if($model===null)
      throw new CHttpException('404','The requested page does not exist.');
    return $model;
  }

  /**
   * Performs the AJAX validation.
   * @param CModel the model to be validated
   */
  protected function performAjaxValidation($model)
  {
    if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
      {
	echo CActiveForm::validate($model);
	Yii::app()->end();
      }
  }
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
   <?php echo $content; ?>
</div><!-- content -->
   <?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/images/konventionLogo.ico" />

    <!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

    <!--[if gte IE 9]>
	<style type="text/css">
	  .gradient {
	  filter: none;
	  }
	</style>
	<![endif]-->

<?php 
	  /*    <!-- CSS Includes -->
    <!-- Twitter Bootstrap -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/plugins/bootstrap/css/bootstrap.min.css" />
    <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/plugins/datatables/media/css/demo_table.css" />
    <!-- Google Prettify -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/plugins/google-code-prettify/prettify.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/plugins/google-code-prettify/sons-of-obsidian.css" />
    <!-- Icons, via Adam Fairhead @ http://fairheadcreative.com -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/plugins/webicons/fc-webicons.css" />
    <!-- Custom -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	  */ ?>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/cssbundle-dev.css"/>

    <title>Konvention</title>
  </head>

  <body>

    <div id="container">

      <!-- Page Header -->
      <div id="header">
	<div id="logo">	    
	  <div id="title"><a href="<?php echo $this->createUrl('site/index') ?>"><?php echo CHtml::encode(Yii::app()->name); ?><sup>&alpha;</sup></a></div>
	  <span id="subtitle"><?php $tagline_arr = array("Consistency is our major export.", 
						  "Helping you write less terrible code.", 
						  "Hoping our consistency will please the robot overlords.", 
						  "Helping you stop reinventing the wheel.", 
						  "How to do it right.", 
						  "So others can read your code.");print $tagline_arr[rand(0,count($tagline_arr) - 1)];?> 
	  </span>
	</div>

	<div id="topnav">
	  <ul>
	    <li><a href="<?php echo $this->createUrl("site/index") ?>">Search</a></li>
	    <li><a href="<?php echo $this->createUrl("site/page", array('view'=>'about')) ?>">About</a></li>

	    <?php if (Yii::app()->user->isGuest): ?>
	    <li><a href="<?php echo $this->createUrl("site/login") ?>">Login</a></li>
	    <li><a href="<?php echo $this->createUrl("user/create") ?>">Register</a></li>
	    <?php else: ?>
	    <li><a href="<?php echo $this->createUrl("user/view/" . Yii::app()->user->name) ?>">Profile</a></li>
	    <li><a href="<?php echo $this->createUrl("site/logout") ?>">Logout</a> [<?php echo Yii::app()->user->name ?>]</li>
	    <?php endif; ?>

	  </ul>
	</div>
      </div>								  
      <!-- End of Page Header -->

      <!-- Page content -->
      <div id="page">
	<div id="alert-page" hidden="hidden">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <p id="message"></p>
	</div>
	<!-- Breadcrumbs -->
     <?php if(isset($this->breadcrumbs)){$this->widget('zii.widgets.CBreadcrumbs', array('separator'=>'<i class="icon-chevron-right"></i> ','links'=>$this->breadcrumbs,));}?>

	<?php echo $content; ?>
      </div><!-- End of page content -->

      <!-- Footer -->
      <div id="footer">
	Copyright &copy; <?php echo date('Y'); ?> by <a href="http://www.vadosware.com">Vadosware</a>.
	<br/>
	All Rights Reserved.
	<br/>
	Powered by <a href="http://www.yiiframework.com/">Yii</a> and <a href="http://twitter.github.com/bootstrap">Twitter Bootstrap</a><br/>
      </div>
      <!-- End of footer -->


    </div><!-- End of pageWrapper -->

    <!-- JS Includes -->
<?php
										     /*    <!-- jQuery -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery/jquery-1.8.2.min.js" type="text/javascript"></script>
    <!-- Twitter Bootstrap -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- Datatables -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/plugins/datatables/media/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <!-- Google Prettify -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/plugins/google-code-prettify/prettify.js" type="text/javascript"></script>
    <!-- jTruncate -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/plugins/jTruncate/jquery.jtruncate.min.js" type="text/javascript"></script>
    <!-- timeago -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/timeago/jquery.timeago.js" type="text/javascript"></script>
   <!-- Modernizr (required for icons) -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/modernizr.js" type="text/javascript"></script>
    <!-- Custom -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/main.js" type="text/javascript"></script>
										     */ 
										     ?>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jsbundle-dev.js" type="text/javascript"></script>
										     
  </body>
</html>