protected/models/BestPractice.php
<?php

/**
 * This is the model class for table "BestPractice".
 *
 * The followings are the available columns in table 'BestPractice':
 * @property integer $bestpractice_id
 * @property string $name
 * @property string $description
 * @property string $snippet
 * @property string $ref_url
 * @property integer $context_id
 */
class BestPractice extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return BestPractice the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'BestPractice';
	}

	/**
	 * @return string that represents the logical name of the model
	 */
	public function semanticName()
	{
		return 'Best Practice';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, description, ref_url, context_id, fk_karma_id', 'required'),
			array('context_id', 'numerical', 'integerOnly'=>true),
			array('name, ref_url', 'length', 'max'=>128),
			array('snippet','safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('bestpractice_id, name, snippet, description, ref_url, context_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'context' => array(self::BELONGS_TO, 'Context', 'context_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'bestpractice_id' => 'Bestpractice',
			'name' => 'Name',
			'description' => 'Description',
			'snippet' => 'Code Snippet',
			'ref_url' => 'Ref Url',
			'context_id' => 'Context',
		);
	}

	/**
	 * Get the id for this Best Practice 
	 * @return integer The best practice id for the model
	 */
	public function id()
	{
	  return $this->bestpractice_id;
	}


	/**
	 * Lookup the Karma object related to this BestPractice
	 */
	public function getKarma(){
	  return Karma::model()->findByPk($this->fk_karma_id);	  
	}


	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search($query, $context)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$query_arr = preg_split("/[\s,.]+/",$query);

		//$criteria->compare('bestpractice_id',$this->bestpractice_id);		
		//Loop and add criteria for each area
		foreach ($query_arr as $query_str){
		$criteria->compare('name',$query_str,true,'OR');
		}
		foreach ($query_arr as $query_str){
		$criteria->compare('description',$query_str,true,'OR');
		}
		//$criteria->compare('name',$query_arr,true,'OR');
		//$criteria->compare('description',$query_arr,true,'OR');
		//$criteria->compare('snippet',$this->snippet,true);
		//$criteria->compare('ref_url',$this->ref_url,true);
		//$criteria->compare('context_id',$this->context_id);

		return new CActiveDataProvider('BestPractice', array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/BestpracticeController.php
<?php

class BestpracticeController extends Controller
{

  public function filters()
  {
    return array( 'accessControl' );
  }

  public function accessRules()
  {
    return array(
		 array('allow', // allow anonymous users to perform 'index' and 'view' actions
		       'actions'=>array('index','view','viewbyname','list','getkarma'),
		       'users'=>array('?'),
		       ),
		 array('allow', //Allow only authenticated users to create and comment 
		       'actions'=>array('index','view','viewbyname','create','submitcomment','addkarma','getkarma','list'),
		       'users'=>array('@'),
		       ),
		 array('allow', // allow admin user do anything they feel like.
		       'users'=>array('vados'),
		       ),
		 array('deny',  // deny all users
		       'users'=>array('*'),
		       ),
		 );
  }

  public function actionIndex()
  {
    $this->render('index');
  }

  /*
   * Produce list of best practices on ajax request (expecting insertion into datatables data)
   */
  public function actionList($context=''){
    //If JSON request, produce listing, else produce html
    if (!YII_DEBUG && !Yii::app()->request->isAjaxRequest) {
      throw new CHttpException('403', 'Forbidden access.');	  
    } else {
      //JSON Headers
      header('Content-Type: application/json; charset="UTF-8"');    
	  
      //Determine context to search for, if there is one
      //Look in the BestPractice+Karma listing, which is a joined to show likes
      $best_practice_list = array();
      if ($context === ''){
	$best_practice_list = BestPracticeKarmaView::model()->findAll();
      } else {
	//Look up the context provided
	$context_obj = Context::model()->findByAttributes(array('name'=>$context));
	if ($context_obj === NULL){ //If the context isn't found, send json error and exit
	  echo json_encode(array('status'=>'error','message'=>'Could not find specified context'));
	  return;
	}
	//Fill up the result array with the specified context
	$best_practice_list = BestPracticeKarmaView::model()->findAllByAttributes(array('context_id'=>$context_obj->context_id));
      }
      
      $result = array('aaData'=>array(), 'aaColumns'=>array(),'aaSorting'=>array());
	  
      //Add data
      foreach ($best_practice_list as $best_practice){
	array_push($result['aaData'], array($best_practice->name,
					    $best_practice->context->name,
					    $best_practice->description,
					    $best_practice->ref_url,
					    $best_practice->likes));
	  }
      
      echo json_encode($result);
    }
  }


  /**
   * Displays a particular model.
   * @param integer $id the ID of the model to be displayed
   */
  public function actionView($id)
  {
    $model = $this->loadModel($id);
    $this->render('view',array('model'=>$model));
  }

  /**
   * Look up and display a Best Practice's data by context name
   * @param string $bestpracticename The contextname of the Context to be retrieved
   */
  public function actionViewByName($contextname,$bestpracticename)
  {
    $model = $this->loadByName($contextname,$bestpracticename);
    $this->render('view',array('model'=>$model));
  }

  /**
   * Returns the Best Practice based on the primary key given in the GET variable.
   * If the data model is not found, an HTTP exception will be raised.
   * @param integer best practice name The best practice name of the model to be loaded
   */
  public function loadByName($contextname,$bestpracticename)
  {
    //Find related context
    $context=Context::model()->findByAttributes(array('name'=>$contextname));
    if($context===null)
      throw new CHttpException('404',"The requested page does not exist, could not find specified context: $contextname");

    //Find the best practice it belongs to
    $model=BestPractice::model()->findByAttributes(array('name'=>$bestpracticename, 'context_id'=>$context->context_id));
    if($model===null)
      throw new CHttpException('404',"The requested page does not exist, could not find specified bestpractice: \"$bestpracticename\"");
    return $model;
  }

  //Expecting name of a context that will be associated with the Best Practice that is to be created
  public function actionCreate($context="")
  {
    $model = new BestPractice;
	  
    //Save new best practice if self-submit
    if (isset($_POST['BestPractice']) && isset($_POST['context'])){
	  
      //Find the context related to this best practice
      $context = Context::model()->find("name=?",array($_POST['context']));
		  
      
      //Create a karma object for this best practice
      $karma = new Karma;
      $karma->attributes = array('type'=> $model->tableName()); 
      $karma->save();
      
      //Update the potential model -- note that context id must be transformed first before being put in	  
      $attribs = $_POST['BestPractice'];
      $attribs['context_id'] = $context->context_id;
      $attribs['fk_karma_id'] = $karma->karma_id;
      $model->attributes= $attribs;
      
      //Attempt to save the model and associated karma object
      if ($model->save()){
	
	//Update the karma object's fk_type_id
	$karma->fk_type_id = $model->bestpractice_id;
	$karma->update();
	
	//Record the creation of the bestpractice
	$activityrecord = new ActivityRecord;
	$new_url = Yii::app()->createUrl('context/' . $context->name . '/bestpractice/' . $model->name);
	$activityrecord->attributes = array('username'=>Yii::app()->user->name,
					    'desc'=>'added a best practice',
					    'fk_type'=>$model->tableName(),
					    'fk_type_id'=>$model->bestpractice_id,
					    'url'=> $new_url,
					    'subject'=>$model->name);
	$activityrecord->save();  
	
	//Redirect the user to the view of the new model
	$this->redirect(array('view','id'=>$model->bestpractice_id));
	
      }  else {
	$this->render('create',array('context'=>$context, 'error'=>"Could not create new Best Practice"));      	
      } 
    }
    
    //Display form if not self-submit
    $this->render('create', array('context'=>$context));
  }
			
  /*    public function actions()
	{
	// return external action classes, e.g.:
	return array(
	'action1'=>'path.to.ActionClass',
	'action2'=>array(
	'class'=>'path.to.AnotherActionClass',
	'propertyName'=>'propertyValue',
	),
	);
	}
  */

  /**
   * Returns the data model based on the primary key given in the GET variable.
   * If the data model is not found, an HTTP exception will be raised.
   * @param integer $id the ID of the model to be loaded
   */
  private function loadModel($id)
  {
    $model=BestPractice::model()->findByPk($id);
    if($model===null)
      throw new CHttpException('404','The requested page does not exist.');
    return $model;
  }


  /**
   * AJAX action that attempts to add a comment to a given Best Practice Model (identified by id)
   * @param integer $id the ID of the model to which the comment belongs
   */
  public function actionSubmitComment($id) {
    
    if (!YII_DEBUG && !Yii::app()->request->isAjaxRequest) {
      throw new CHttpException('403', 'Forbidden access.');
    }
	  	  
    //JSON Headers
    header('Content-Type: application/json; charset="UTF-8"');

    //Create a new comment and populate it with http headers
    $new_comment = new Comment;
    if (isset($_POST['comment'])) {
      $new_comment->username = Yii::app()->user->name;
      $new_comment->type = "BestPractice";
      $new_comment->fk_type_id = $id;
      $new_comment->comment = $_POST['comment']; //This needs to be escaped
    }

    //	$debug = print_r($new_comment->attributes, true);
      
    //Attempt to save the new comment
    if ($new_comment->save()){     
      echo json_encode(array('status'=>'success',
			     'message'=> 'Comment Saved',
			     'comment'=>array('username'=>$new_comment->username,
					      'submitted_at'=>$new_comment->submitted_at,
					      'text'=>$new_comment->comment)));
    } else {
      echo json_encode(array('status'=>'error',
			     //'debug'=>print_r($new_comment->getErrors(),true),
			     'message'=> 'Uh-oh, it looks like your comment could not be saved... Please wait a while and try again'));
    }
  }


  /** 
   * AJAX action to retrieve karma of requested best practice
   * @param integer $id The ID of the best practice
   */
  public function actionGetKarma($id) {
    if (!YII_DEBUG && !Yii::app()->request->isAjaxRequest) {
      throw new CHttpException('403', 'Forbidden access.');
    }
	  	  
    //JSON Headers
    header('Content-Type: application/json; charset="UTF-8"');

    $bestpractice = $this->loadModel($id);
    $karma = $bestpractice->getKarma();	
    $opinion = Yii::app()->user->isGuest ? '' : KarmaRecord::model()->findByAttributes(array('type'=> 'bestpractice',
											     'fk_type_id' => $bestpractice->bestpractice_id,
											     'user_id'=> Yii::app()->user->id))->opinion;
    
    echo json_encode(array('karma'=>$karma->total_karma(),
			   'likes'=> (int) $karma->likes,
			   'dislikes'=> (int) $karma->dislikes,
			   'opinion'=> strtolower($opinion)));
    return;
    
  }

  /**
   * AJAX action that attempts to add a like to a given Best Practice Model (identified by id)
   * @param integer $id the ID of the model to which the comment belongs
   */
  public function actionAddKarma($id) {
    
    if (!YII_DEBUG && !Yii::app()->request->isAjaxRequest) {
      throw new CHttpException('403', 'Forbidden access.');
    }
	  	  
    //JSON Headers
    header('Content-Type: application/json; charset="UTF-8"');

    //Allow only valid opinion parameters
    if (!isset($_GET['opinion']) || ($_GET['opinion'] !== "LIKE" &&
				     $_GET['opinion'] !== "DISLIKE")) {
      echo json_encode(array('status'=>'error',
			     'message'=>'Invalid Request.'));
      return;
    }
				
    //Load the new opinion, bestpractice, karma and karmarecord models
    $new_opinion = $_GET['opinion'];
    $is_new = false;
    $bestpractice = $this->loadModel($id);
    $karma = $bestpractice->getKarma();	

protected/views/bestpractice/create.php
<?php
/* @var $context name of the Context to submit the best practice under (autoselected in context list) */
/* @var $error String to represent an error that occured */

$this->breadcrumbs=array(
			 'Best Practice'=>array('bestpractice/index'),
			 'New Best Practice',
			 );
?>

<?php 
 //Print errors if there is one
print (isset($error)) ? '<div class="alert alert-error">' . $error . '</div>' : ""; 
?>

<h1>Suggest a Best Practice</h1>

<p>
Best Practices are techniques and methods that produce better results than the naive approach, that programmers should try and follow.
</p>

<p>
Are there any best practices that you have followed that have worked wonders for you? Suggest it below!
</p>

  <br/>

  <form id="frmSuggestBestPractice" action="<?php echo Yii::app()->createUrl('bestpractice/create')?>" method="post">

  <label for="frmSuggestBestPractice-field-name">Best Practice Name</label>
  <input type="text" placeholder="Name" id="frmSuggestBestPractice-field-name" name="BestPractice[name]" />
  <br/>

  <label for="frmSuggestBestPractice-field-description">Best Practice Description</label>
  <textarea rows="10" cols="50" placeholder="Description" id="frmSuggestBestPractice-field-description" name="BestPractice[description]"></textarea>
  <br/>

  <label for="frmSuggestBestPractice-field-snippet">Code Snippet</label>
  <textarea rows="10" cols="50" placeholder="Snippet" id="frmSuggestBestPractice-field-snippet" name="BestPractice[snippet]"></textarea>
  <br/>

  <label for="frmSuggestBestPractice-field-ref_url">Best Practice Reference URL</label>
  <input type="text" placeholder="Reference URL" id="frmSuggestBestPractice-field-ref_url" name="BestPractice[ref_url]" />
  <br/>

  <label for="frmSuggestBestPractice-field-context">Related Context</label>
  <select id="frmSuggestBestPractice-field-context" name="context">
    <?php 
       $context_list = Context::model()->findAll();
    foreach ($context_list as $context_obj){    
      print "<option" . (($context_obj->name === $context) ? " selected=\"selected\"" : "") . ">";
      print $context_obj->name . "</option>\n"; 
      }   
    ?>
  </select>
  <br/>

  <br/>
  <button type="submit" class="btn btn-large btn-success" id="btnSubmitBestPractice">Submit Best Practice</button>
  </form>

protected/views/bestpractice/index.php
<?php
/* @var $this BestpracticeController */

$this->breadcrumbs=array(
	'Best Practice');
?>

<h1>Most Popular Best Practices</h1>

<table data-src="<?php echo Yii::app()->createUrl('bestpractice/list'); ?>" class="table table-condensed table-bordered" id="bp_list">
  <thead>
    <tr>
      <th>Name</th>
      <th>Context</th>
      <th>Description</th>
      <th>Reference URL</th>
      <th>Likes</th>  
    </tr>
  </thead>
  <tbody> 
  </tbody>
</table>

protected/views/bestpractice/view.php
<?php
   /* @var $this BestpracticeController */
   /* @var $model BestPractice */

//Lookup context
$context = Context::model()->findByPk($model->context_id);

   $this->breadcrumbs=array(
			    'Context'=>array('context/index'),
			    $context->name=>array('context/view/' . $context->name),
			    'Best Practice',			   
			    );

#Clean some data about to be displayed on the page
$snippet_safe = htmlspecialchars($model->snippet);
$desc_safe = nl2br(htmlspecialchars($model->description));
$ref_url_safe = htmlspecialchars($model->ref_url);

?>


<h1><?php echo $model->name ?></h1>
<?php $this->renderPartial("/karma/_widget", array('model'=>$model,'karma'=>$model->getKarma())); ?>


<br/>
<br/>
<dl class="dl-horizontal">

  <dt>Snippet</dt>
     <dd><pre class="prettyprint" style="padding:.5em;"><?php echo $snippet_safe ?></pre></dd>
  <br/>

  <dt>Description</dt>
     <dd><?php echo $desc_safe ?></dd>
  <br/>

  <dt>Context</dt>
  <dd><a href="<?php echo Yii::app()->createUrl('context/view/' . $context->name) ?>"><?php echo $context->name ?></a></dd>
  <br/>

  <dt>Convention Type</dt>
  <dd><?php echo $model->semanticName() ?></dd>
  <br/>

  <dt>Reference URL</dt>
  <dd><a href="<?php echo $ref_url_safe ?>"><?php echo $ref_url_safe ?></a></dd>  
  <br/>
</dl>

<?php $this->renderPartial("/comment/_list", array('model'=>$model)); ?>